name: 'Legal Teammates'
description: 'Find teammates to work with on the projects in the DD2482 course.'
inputs:
  github-token: 
    description: "Github secret"
    required: true
  list-branch:
    description: "Branch name containing the list of students"
    required: true
  list-file:
    description: "Path of the file containing the list of students"
    required: true
  main-branch:
    description: "Branch name where the course is being held"
    required: true
outputs:
  legal-teammates: # id of output
    description: 'A comment with a list of legal teammates'
runs:
  using: 'node12'
  main: 'dist/index.js'