on: 
  issues:
    types: [opened, reopened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: testing
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello world action step
      id: hello
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
